const mokeDataForPayType = [
  {
    code: "food",
    name: "食品饮料",
    desc: "民以食为天",
    children: [
      {
        id: 1,
        code: "eat",
        name: "早中晚餐",
        desc: "吃饭饭",
        icon: "food",
      },
      {
        id: 2,
        code: "buyvege",
        name: "买菜",
        desc: "买菜撒",
        icon: "vegetables",
      },
      { id: 3, code: "fruit", name: "水果", desc: "吃水果", icon: "fruits" },
      { id: 4, code: "drink", name: "饮料", desc: "就是喝的", icon: "snacks" },
      { id: 4, code: "snacks", name: "零食", desc: "就是喝的", icon: "snacks" },
    ],
  },
  {
    code: "externalDress",
    name: "外在打扮",
    desc: "就是你穿的戴的",
    children: [
      {
        id: 1,
        code: "clothingShoe",
        name: "衣服鞋帽",
        desc: "你的衣服鞋子帽子",
        icon: "clothes",
      },
      {
        id: 2,
        code: "beautyHair",
        name: "美容理发",
        desc: "剪头发美容",
        icon: "cosmetology",
      },
      {
        id: 3,
        code: "makeUp",
        name: "彩妆美妆",
        desc: "女性化妆",
        icon: "cosmetics",
      },
      {
        id: 4,
        code: "jewelry",
        name: "珠宝首饰",
        desc: "戒指啊那些",
        icon: "food",
      },
    ],
  },
  {
    code: "family",
    name: "居家生活",
    desc: "在家要花费的",
    children: [
      {
        id: 1,
        code: "roomRent",
        name: "房租",
        desc: "租房子要花的钱，心塞",
        icon: "housing",
      },
      {
        id: 2,
        code: "powerRate",
        name: "电费",
        desc: "电脑花的电",
        icon: "electric",
      },
      {
        id: 3,
        code: "waterRate",
        name: "水费",
        desc: "洗澡洗衣服上厕所",
        icon: "food",
      },
      {
        id: 4,
        code: "upkeep",
        name: "维修费",
        desc: "通下水道，修空调",
        icon: "water",
      },
      {
        id: 4,
        code: "daliyUse",
        name: "生活用品",
        desc: "卫生纸啊那些",
        icon: "daily-necessities",
      },
      {
        id: 4,
        code: "furniture",
        name: "家具家电",
        desc: "洗衣机电视那些",
        icon: "home",
      },
      {
        id: 4,
        code: "mortgage",
        name: "房贷",
        desc: "买了房子的，我买不起",
        icon: "housing",
      },
    ],
  },
  {
    code: "transportationTravel",
    name: "交通出行",
    desc: "上班地铁公交车打车",
    children: [
      {
        id: 1,
        code: "busSubway",
        name: "公交地铁",
        desc: "上班的",
        icon: "traffic",
      },
      {
        id: 2,
        code: "trainPlane",
        name: "火车飞机",
        desc: "旅行的，虽然我没坐过",
        icon: "plane",
      },
      {
        id: 3,
        code: "taxiRental",
        name: "打车租车",
        desc: "半夜没地铁了",
        icon: "car",
      },
      {
        id: 4,
        code: "carLoan",
        name: "车贷",
        desc: "买了车，贷款的钱",
        icon: "car",
      },
      {
        id: 5,
        code: "maintenance",
        name: "保养维修",
        desc: "买了车得花钱，还好我买不起",
        icon: "car-repair",
      },
      {
        id: 6,
        code: "insure",
        name: "保险",
        desc: "车的保险，还好我没车",
        icon: "car",
      },
      {
        id: 7,
        code: "violationTicket",
        name: "违章罚款",
        desc: "车的，还好我没车",
        icon: "car",
      },
      {
        id: 8,
        code: "parkingRate",
        name: "停车费",
        desc: "车的，还好我没车",
        icon: "parking",
      },
      {
        id: 9,
        code: "oilRate",
        name: "加油费",
        desc: "车的，还好我没车",
        icon: "oil",
      },
    ],
  },
  {
    code: "entertainment",
    name: "休闲娱乐",
    desc: "玩耍的撒",
    children: [
      {
        id: 1,
        code: "game",
        name: "游戏",
        desc: "游戏花费",
        icon: "fun",
      },
      {
        id: 2,
        code: "movie",
        name: "电影",
        desc: "看电影的钱吧，我一个人可不看",
        icon: "user",
      },
      {
        id: 3,
        code: "sportsFitness",
        name: "运动健身",
        desc: "锻炼身体的",
        icon: "user",
      },
      {
        id: 4,
        code: "vip",
        name: "网络会员",
        desc: "qq会员那种",
        icon: "user",
      },
      {
        id: 4,
        code: "other",
        name: "其他娱乐",
        desc: "其他的吧",
        icon: "user",
      },
    ],
  },
  {
    code: "medicalCare",
    name: "医疗保健",
    desc: "看病啊体检啊那些",
    children: [
      {
        id: 1,
        code: "medicinal",
        name: "药物费",
        desc: "买药花的钱",
        icon: "reimbursement",
      },
      {
        id: 2,
        code: "treatmentFee",
        name: "治疗费",
        desc: "花钱看病的",
        icon: "reimbursement",
      },
      {
        id: 3,
        code: "hospitalizationExpenses",
        name: "住院费",
        desc: "住院治疗的，我可不想",
        icon: "reimbursement",
      },
      {
        id: 4,
        code: "nursingFee",
        name: "护理费",
        desc: "情人照顾啥的",
        icon: "reimbursement",
      },
    ],
  },
  {
    code: "education",
    name: "文娱教育",
    desc: "学习相关的",
    children: [
      {
        id: 1,
        code: "material",
        name: "学习资料",
        desc: "学习资料的钱",
        icon: "book",
      },
      {
        id: 2,
        code: "stationery",
        name: "学习用品",
        desc: "学习用品",
        icon: "book",
      },
      {
        id: 3,
        code: "textualResearch",
        name: "考证报名",
        desc: "四六级或者其他的玩意儿",
        icon: "education",
      },
    ],
  },
  {
    code: "humanRelationship",
    name: "人情往来",
    desc: "人情往来",
    children: [
      {
        id: 1,
        code: "treat",
        name: "请客送礼",
        desc: "请客送礼的钱",
        icon: "cash-gift",
      },
      {
        id: 2,
        code: "loveFamily",
        name: "爱的家人",
        desc: "给家人用的撒",
        icon: "friends",
      },
      {
        id: 3,
        code: "forUs",
        name: "属于我们",
        desc: "害，可惜时单身狗",
        icon: "social",
      },
    ],
  },
  {
    code: "otherPay",
    name: "其他杂项",
    desc: "其他用的吧",
    children: [
      {
        id: 1,
        code: "lose",
        name: "意外丢失",
        desc: "意外丢失的钱",
        icon: "financing",
      },
      {
        id: 2,
        code: "badDebts",
        name: "烂账损失",
        desc: "不还钱就很难受",
        icon: "financing",
      },
      {
        id: 3,
        code: "otherExpenses",
        name: "其他支出",
        desc: "不晓得花哪儿去了",
        icon: "financing",
      },
    ],
  },
];

module.exports = { mokeDataForPayType };
